version: latest
published_at: "20260820"
installer:
  path: installers/latest/server-setup.run
  sha256: 6ce762e2ac96198c8a1fad6b233c7ad9481884c8a8af6865a5f6fd8436cb0dca
templates:
  path: templates/latest
  manifest: manifest.sha256
  archives:
    - aether.tar.gz
    - alist.tar.gz
    - any-auto-register.tar.gz
    - axonhub.tar.gz
    - certimate.tar.gz
    - cliproxyapi.tar.gz
    - cpa-manager-plus.tar.gz
    - domain-admin.tar.gz
    - metapi.tar.gz
    - mysql57.tar.gz
    - mysql8.tar.gz
    - new-api.tar.gz
    - nginx.tar.gz
    - octopus.tar.gz
    - octopus-plus.tar.gz
    - pgsql.tar.gz
    - redis6.tar.gz
    - resin.tar.gz
    - sub2api.tar.gz
