version: v1.0.0
installer:
  path: installers/v1.0.0/server-setup.run
  sha256: 7b46d65c1f2bdf8e34316e7a07d7d730f9419150e9a8c29fa0f5e0cc18032587
templates:
  path: templates/v1.0.0
  manifest: manifest.sha256
  archives:
    - certimate.tar.gz
    - domain-admin.tar.gz
    - mysql57.tar.gz
    - mysql8.tar.gz
    - nginx.tar.gz
    - pgsql.tar.gz
    - redis6.tar.gz
